package visionary.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jsondoc.core.annotation.ApiObject;
import org.jsondoc.core.annotation.ApiObjectField;

@ApiObject
@Entity
@Table(name = "filter")
public class Filter {

    @ApiObjectField(description = "An autogenerated id (unique for each user in the db)", required=true)
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long idFilter;

    @ApiObjectField(description = "The parameter (name) of the filter", required=true)
	@NotNull
	private String parameter;
    
    @ApiObjectField(description = "The value of the filter, can be null", required=false)
	private Integer value;

    /*@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCorrectionProfileResult", insertable=false, updatable=false, nullable=false)*/
    //private CorrectionProfileResult correctionProfileResult;

	public Filter() {
	}

	public Filter(long idFilter) {
		this.idFilter = idFilter;
	}
	
	/**
	 * constructor of Filter from JSON data to mysql entity
	 * @param parameter
	 * @param value
	 */
	public Filter(String parameter, Integer value, CorrectionProfileResult correctionProfileResult) {
		this.parameter = parameter;
		this.value = value;
		//this.correctionProfileResult = correctionProfileResult;
	}
	
	/**
	 * @return the idFilter of the correction profile result's filter of the user in mysql db
	 */
	public long getIdFilter() {
		return idFilter;
	}
	
	/**
	 * @return the parameter of the filter
	 */
	public String getParameter() {
		return parameter;
	}

	/**
	 * @param parameter the parameter of the filter
	 */
	public void setParameter(String parameter) {
		this.parameter = parameter;
	}
	
	/**
	 * @return the value
	 */
	public Integer getValue() {
		return value;
	}
	/**
	 * @param value the value to set
	 */
	public void setValue(Integer value) {
		this.value = value;
	}
	
	/*public void setCorrectionProfileResult(CorrectionProfileResult correctionProfileResult) {
		this.correctionProfileResult = correctionProfileResult;
	}*/
	
}
