package visionary.models;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.jsondoc.core.annotation.ApiObject;
import org.jsondoc.core.annotation.ApiObjectField;

@ApiObject
@Entity
@Table(name = "user", uniqueConstraints= @UniqueConstraint(columnNames = {"email"})) 
public class User {

    @ApiObjectField(description = "An autogenerated id (unique for each user in the db)", required=true)
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long idUser;

    @ApiObjectField(description = "The email of the user, that have to be unique", required=true)
	@NotNull
	private String email;
    
    @ApiObjectField(description = "The name of the user", required=true)
	@NotNull
	private String name;
    
    @ApiObjectField(description = "The firstname of the user", required=true)
	@NotNull
	private String firstname;
    
    @ApiObjectField(description = "The age of the user", required=true)
	@NotNull
	private Integer age;
    
    @ApiObjectField(description = "The sex of the user", required=true)
	@NotNull
	private Boolean sex;
    
    @ApiObjectField(description = "The user's creation date (date of creation in mongoDB)", required=true)
	@NotNull
	private Long dateCreated;

    @ApiObjectField(description = "The user's correction profile results linked by id_user", required=true)
	@NotNull
    @OneToMany(fetch = FetchType.EAGER, /*mappedBy = "user",*/cascade = {CascadeType.ALL})
    @JoinColumn(name = "idUser")
	private List<CorrectionProfileResult> correctionProfileResults;

	// Public methods

	public User() { }

	public User(long idUser) { 
		this.idUser = idUser;
	}

	/**
	 * constructor of User from JSON data to mysql entity
	 * @param name
	 * @param firstname
	 * @param email
	 * @param age
	 * @param sex
	 * @param dateCreated
	 * @param correctionProfileResults
	 */
	public User(String name, String firstname, String email, Integer age, Boolean sex, Long dateCreated, List<CorrectionProfileResult> correctionProfileResults) {
		this.email = email;
		this.name = name;
		this.firstname = firstname;
		this.age = age;
		this.sex = sex;
		this.dateCreated = dateCreated;
		this.correctionProfileResults = correctionProfileResults;
	}

	/**
	 * @return the idUser of the user in mysql db
	 */
	public long getIdUser() {
		return idUser;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the firstname
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * @param firstname the firstname to set
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the age
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * @param age the age to set
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * @return the sex
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * @param sex the sex to set
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * @return the date_created
	 */
	public Long getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param date_created the date_created to set
	 */
	public void setDateCreated(Long dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	/**
	 * @return correctionProfileResults a list of correction profile results of the user
	 */
	public List<CorrectionProfileResult> getCorrectionProfileResults() {
		return correctionProfileResults; 
	}
	
	/**
	 * @param correctionProfileResultTab to set
	 */
	public void setCorrectionProfileResults(List<CorrectionProfileResult> correctionProfileResults) {
		this.correctionProfileResults = correctionProfileResults;
	}

}

